#!/bin/sh

# install the default password (admin/admin)
# TODO: make this read default passwords from configuration file
SHADOW_FILE=/etc/orange/shadow

mkdir -p $(dirname $SHADOW_FILE)
rm -f $SHADOW_FILE
which sha1sum || { echo "ERROR: you need to have sha1sum installed for JUCI to work!"; return -1; }
echo "admin `printf admin|sha1sum | awk '{printf $1}'`" > $SHADOW_FILE
chmod 700 $SHADOW_FILE

# install the admin user into the jucid config

cat >> /etc/config/jucid << EOF
config login admin
	list acls 'juci*'
	list acls 'user-admin'
EOF

install_event_config(){
	cat >> /etc/config/juci << EOF
config juci_event 'juci_event'
	list filter firewall.ssh
	list filter network.netifd
	list filter network.dnmasq
	list filter system.kernel
	list filter system.ntp
	list filter iptv.mcpd
EOF
}

install_ethernet_pages(){
	cat >> /etc/config/juci << EOF
config menu
	option path 'internet'
	option page 'network'
	option redirect 'internet-ethernet'
	list acls 'user-support'

config menu
	option path 'internet/ethernet'
	option page 'internet-ethernet'
	list acls 'juci-network-netifd'
	list acls 'user-support'
EOF
}

# install the default menus if they are not already in the config
uci -q get juci.@menu[0] || {
	cat >> /etc/config/juci << EOF
config menu
	option path 'overview'
	option page 'overview'
EOF
	install_event_config
	install_ethernet_pages
	
	cat >> /etc/config/juci << EOF
config menu
	option path 'internet/ethernet/vlan'
	option page 'netifd-vlan-config'
	list acls 'juci-network-netifd'
	list acls 'user-support'

config menu
	option path 'internet/network'
	option page 'internet-network'
	list acls 'juci-network-netifd'
	list acls 'user-support'

config menu
	option path 'internet/routes'
	option page 'internet-routes'
	list acls 'juci-network-netifd'
	list acls 'user-support'

config menu
	option path 'internet/firewall'
	option page 'internet-firewall'
	list acls 'juci-firewall-fw3'

config menu
	option path 'internet/firewall/zones'
	option page 'internet-firewall-zones'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'

config menu
	option path 'internet/firewall/rules'
	option page 'internet-firewall-rules'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'

config menu
	option path 'internet/firewall/forwarding'
	option page 'internet-firewall-forwarding'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'

config menu
	option path 'internet/firewall/port_mapping'
	option page 'internet-firewall-port-mapping'
	list acls 'juci-firewall-fw3'
	option modes 'expert'

config menu
	option path 'internet/firewall/dmz'
	option page 'internet-firewall-dmz'
	list acls 'juci-firewall-fw3'
	option modes 'expert'

config menu
	option path 'internet/parental_control'
	option page 'internet-parental-control'
	list acls 'juci-firewall-fw3'

config menu
	option path 'internet/services'
	option page 'internet-services'
	list acls 'juci-network-netifd'

config menu
	option path 'internet/services/minidlna'
	option page 'internet-services-minidlna'
	list acls 'juci-minidlna'

config menu
	option path 'internet/services/ntp'
	option page 'internet-services-ntp'
	list acls 'juci-mod-system'

config menu
	option path 'internet/services/upnp'
	option page 'upnpd-settings'
	list acls 'juci-upnp'

config menu
	option path 'internet/services/ddns'
	option page 'internet-services-ddns'
	list acls 'juci-ddns'

config menu 
	option path 'internet/services/dhcp'
	option page 'dhcp-settings'
	list acls 'juci-dnsmasq-dhcp'
	list acls 'user-support'

config menu 
	option path 'internet/services/snmpd'
	option page 'snmpd-config'
	list acls 'juci-snmpd'
	list acls 'user-support'

config menu
	option path 'internet/services/samba'
	option page 'internet-services-samba'
	list acls 'juci-samba'

config menu
	option path 'wifi'
	option page 'wireless'
	option redirect 'wireless-general'

config menu 
	option path 'wifi/general'
	option page 'wireless-general'
	list acls 'juci-openwrt-wireless'

config menu 
	option path 'wifi/devices'
	option page 'wireless-devices'
	list acls 'juci-openwrt-wireless'

config menu 
	option path 'wifi/interfaces'
	option page 'wireless-interfaces'
	list acls 'juci-openwrt-wireless'

config menu 
	option path 'wifi/clients'
	option page 'wireless-clients'
	list acls 'juci-openwrt-wireless'

config menu
	option path 'settings'
	option page 'system'
	option redirect 'settings-system'

config menu
	option path 'settings/system'
	option page 'settings-system'
	list acls 'juci-mod-system'

config menu
	option path 'settings/password'
	option page 'settings-password'
	list acls 'juci-mod-system'

config menu
	option path 'settings/upgrade'
	option page 'settings-upgrade'
	list acls 'juci-sysupgrade'
	list acls 'user-support'

config menu
	option path 'settings/configuration'
	option page 'settings-configuration'
	list acls 'juci-mod-system'

config menu
	option path 'settings/management'
	option page 'settings-management'
	list acls 'juci-mod-system'
	list acls 'user-support'

config menu
	option path 'settings/management/dropbear'
	option page 'settings-management-dropbear'
	list acls 'juci-dropbear'
	list acls 'user-support'

config menu
	option path 'settings/management/uhttpd'
	option page 'page-uhttpd-settings'
	list acls 'juci-uhttpd'
	list acls 'user-support'

config menu
	option path 'settings/management/services'
	option page 'internet-firewall-services'
	list acls 'juci-firewall-fw3'
	list acls 'user-support'

config menu
	option path 'settings/services'
	option page 'settings-services'
	list acls 'juci-mod-system'
	list acls 'user-support'

config menu
	option path 'status'
	option page 'status'
	option redirect 'status-system'

config menu
	option path 'status/system'
	option page 'status-system'
	list acls 'juci-mod-system'

config menu
	option path 'status/system/processes'
	option page 'status-system-processes'
	list acls 'juci-mod-system'

config menu
	option path 'status/tv'
	option page 'status-tv'
	list acls 'juci-igmpsnoop'

config menu
	option path 'status/usb'
	option page 'status-usb'
	list acls 'juci-usb'

config menu
	option path 'status/network'
	option page 'status-network'
	list acls 'juci-network-netifd'

config menu
	option path 'status/network/clients'
	option page 'netifd-status-clients'
	list acls 'juci-network-netifd'

config menu
	option path 'status/network/routes'
	option page 'status-network-routes'
	list acls 'juci-network-netifd'

config menu
	option path 'status/network/upnpd'
	option page 'upnpd-status'
	list acls 'juci-upnp'

config menu 
	option path 'status/network/dhcp'
	option page 'dhcp-status'
	list acls 'juci-dhcp'

config menu
	option path 'status/network/nat'
	option page 'status-network-nat'
	list acls 'juci-network-netifd'

config menu
	option path 'status/diagnostics'
	option page 'status-diagnostics'
	list acls 'juci-diagnostics'
EOF
	cat >> /etc/config/juci << EOF
config menu
	option path 'status/events'
	option page 'status-events'
	option modes 'expert'

config menu
	option path 'status/restart'
	option page 'status-restart'
EOF
}

# install the default menus if they are not already in the config
ubus call uci delete '{"config":"rpcd","type":"login"}'
ubus call uci commit '{"config":"rpcd"}'

cat >> /etc/config/rpcd << EOF
config login
	option username 'admin'
	option password '\$p\$admin'
	list write 'user-admin'
	list write 'user-support'
	list write 'juci-ddns'
	list write 'juci-diagnostics'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-igmpinfo'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-mod-system-admin'
	list write 'juci-network-netifd'
	list write 'juci-samba'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-uhttpd'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'

config login
	option username 'support'
	option password '\$p\$support'
	list write 'user-support'
	list write 'juci-ddns'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-igmpinfo'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-network-netifd'
	list write 'juci-samba'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-uhttpd'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'

config login
	option username 'user'
	option password '\$p\$user'
	list write 'user-user'
	list write 'juci-ddns'
	list write 'juci-dnsmasq-dhcp'
	list write 'juci-dropbear'
	list write 'juci-ethernet'
	list write 'juci-event'
	list write 'juci-firewall-fw3'
	list write 'juci-igmpinfo'
	list write 'juci-minidlna'
	list write 'juci-mod-status'
	list write 'juci-mod-system'
	list write 'juci-network-netifd'
	list write 'juci-samba'
	list write 'juci-snmpd'
	list write 'juci-sysupgrade'
	list write 'juci-uhttpd'
	list write 'juci-upnp'
	list write 'juci-usb'
	list write 'core'
	list write 'unauthenticated'
EOF
/etc/init.d/rpcd restart

# create redirect cgi if luci exist
[ -f /www/cgi-bin/luci ] && {
  mv /www/cgi-bin/luci /www/cgi-bin/luci-original
  cat >> /www/cgi-bin/luci << EOF
#!/usr/sbin/bash
echo "Content-type: text/html"
echo
echo "<html><head></head><body><a href="/">Click here to go to new JUCI webgui.</a></body></html>"
EOF
}

exit 0
